### ISSUE TITLE
post-checkout fails when checking out a commit SHA

### ISSUE THREAD

**Issue by rheaditi** [ClearTax/pivotal-flow#12]
![image](https://user-images.githubusercontent.com/6426069/65041614-cc633c00-d974-11e9-8c9d-cb9beac8e5aa.png)

```sh
Error: Command failed: git symbolic-ref --short -q HEAD
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
```
when checking out a SHA

**Comment by rheaditi** [comment]
Also fails when running rebase.
